Repository hojoon7807/hehwa-ios, pull requests merged in 2022-01, with the labels that each got.

#22 Chore/#18 calendar design2
  IOS_Study/Screen/Home/Cell/CVC/MemoCVC.swift
  IOS_Study/Screen/Home/Controller/HomeVC.swift
  IOS_Study/Screen/Home/Storyboard/Home.storyboard
Labels: bug, 홈탭, 윤경, View

#26 Feat/#25 custom navi bar 구현
  IOS_Study.xcodeproj/project.pbxproj
  IOS_Study/Screen/Home/Controller/HomeVC.swift
  IOS_Study/Screen/Home/Controller/SideMenuVC.swift
  IOS_Study/Screen/Home/Storyboard/Home.storyboard
  IOS_Study/Screen/NavigationBar/CustomNB.swift
  IOS_Study/Screen/NavigationBar/CustomNB.xib
Labels: 윤경, add

#28 FEAT: 소셜 로그인 제외한 로그인 기능 구현
  IOS_Study.xcodeproj/project.pbxproj
  IOS_Study/Global/Class/Auth.swift
  IOS_Study/Global/Class/Response.swift
  IOS_Study/Global/Extension/Notification+.swift
  IOS_Study/Global/Factory/TypeOfViewController.swift
  IOS_Study/Global/Struct/Identifiers.swift
  IOS_Study/Global/Struct/Login.swift
  IOS_Study/Screen/Login/Controller/LoginVC.swift
  IOS_Study/Screen/Login/Storyboard/Login.storyboard
  IOS_Study/Screen/Signup/Controller/SignupVC.swift
  IOS_Study/Screen/Signup/Storyboard/Signup.storyboard
  IOS_Study/Support/AppController.swift
  IOS_Study/Support/AppDelegate.swift
  IOS_Study/Support/Assets.xcassets/LoginButtonColor.colorset/Contents.json
  Podfile
  Podfile.lock
Labels: 호준, Feature, 로그인

#31 [ADD]: 소셜 로그인 기능 구현
  IOS_Study.xcodeproj/project.pbxproj
  IOS_Study/Global/Class/AppAuth.swift
  IOS_Study/Global/Class/Auth.swift
  IOS_Study/Global/Class/KeychainHelper.swift
  IOS_Study/Global/Class/Response.swift
  IOS_Study/Global/Struct/JwtToken.swift
  IOS_Study/Screen/Home/Controller/SideMenuVC.swift
  IOS_Study/Screen/Login/Controller/LoginVC.swift
  IOS_Study/Screen/Login/Storyboard/Login.storyboard
  IOS_Study/Support/AppController.swift
  IOS_Study/Support/AppDelegate.swift
  IOS_Study/Support/Info.plist
Labels: 호준, 로그인, add

#33 Feat/#29 MyPage 프로토 프레임 구현
  IOS_Study.xcodeproj/project.pbxproj
  IOS_Study/Global/Struct/Identifiers.swift
  IOS_Study/Screen/Home/Controller/HomeVC.swift
  IOS_Study/Screen/MyPage/Cell/TVC/AllSubjectsDataTVC.swift
  IOS_Study/Screen/MyPage/Cell/TVC/SubjectTVC.swift
  IOS_Study/Screen/MyPage/Controller/MyPageVC.swift
  IOS_Study/Screen/MyPage/Controller/ProfileImageVC.swift
  IOS_Study/Screen/MyPage/Storyboard/MyPage.storyboard
  IOS_Study/Screen/MyPage/Storyboard/ProfileImage.storyboard
  IOS_Study/Screen/NavigationBar/CustomNB.swift
  IOS_Study/Support/Assets.xcassets/Number.imageset/Contents.json
  IOS_Study/Support/Assets.xcassets/Number.imageset/Number.png
  IOS_Study/Support/Assets.xcassets/Number.imageset/Number_Dark.png
  IOS_Study/Support/Assets.xcassets/ParentsPhone.imageset/Contents.json
  IOS_Study/Support/Assets.xcassets/ParentsPhone.imageset/ParentsPhone.png
  IOS_Study/Support/Assets.xcassets/ParentsPhone.imageset/ParentsPhone_Dark.png
  IOS_Study/Support/Assets.xcassets/SampleProfileImg.imageset/Contents.json
  IOS_Study/Support/Assets.xcassets/SampleProfileImg.imageset/sampleProfileImg.png
  IOS_Study/Support/Assets.xcassets/School.imageset/Contents.json
  IOS_Study/Support/Assets.xcassets/School.imageset/School.png
  IOS_Study/Support/Assets.xcassets/School.imageset/School_Dark.png
Labels: 마이페이지탭, 윤경, Feature, View

#35 Chore/#34 home constraint
  IOS_Study.xcodeproj/project.pbxproj
  IOS_Study/Screen/Home/Controller/HomeVC.swift
  IOS_Study/Screen/Home/Storyboard/Home.storyboard
  IOS_Study/Screen/TabBar/Storyboard/TabBar.storyboard
Labels: 홈탭, 윤경, View

#37 Feature/#32 chatting
  .gitignore
  IOS_Study.xcodeproj/project.pbxproj
  IOS_Study.xcodeproj/xcshareddata/xcschemes/IOS_Study.xcscheme
  IOS_Study/Global/Class/DismissTransition.swift
  IOS_Study/Global/Class/PresentTransition.swift
  IOS_Study/Global/Factory/TypeOfViewController.swift
  IOS_Study/Global/Struct/ChattingInfo.swift
  IOS_Study/Global/Struct/Identifiers.swift
  IOS_Study/Screen/Chatting/Cell/TVC/ChattingListTVC.swift
  IOS_Study/Screen/Chatting/Controller/AddChattingVC.swift
  IOS_Study/Screen/Chatting/Controller/ChattingVC.swift
  IOS_Study/Screen/Chatting/Controller/StartChattingVC.swift
  IOS_Study/Screen/Chatting/Storyboard/AddChatting.storyboard
  IOS_Study/Screen/Chatting/Storyboard/Chatting.storyboard
  IOS_Study/Screen/Chatting/Storyboard/StartChatting.storyboard
  IOS_Study/Screen/Home/Storyboard/Home.storyboard
  IOS_Study/Screen/Home/Storyboard/SideMenu.storyboard
  IOS_Study/Screen/MyPage/Storyboard/MyPage.storyboard
  IOS_Study/Screen/NavigationBar/CustomNB.xib
  IOS_Study/Support/Assets.xcassets/Add.imageset/Add.png
  IOS_Study/Support/Assets.xcassets/Add.imageset/Contents.json
  IOS_Study/Support/Assets.xcassets/Add_Circle.imageset/Add_Circle.png
  IOS_Study/Support/Assets.xcassets/Add_Circle.imageset/Contents.json
  IOS_Study/Support/Assets.xcassets/CfColor.colorset/Contents.json
Labels: 채팅탭, 호준, Feature, View

#39 Feature/#38 add chatting
  IOS_Study.xcodeproj/project.pbxproj
  IOS_Study/Global/Extension/UINavigationController+.swift
  IOS_Study/Global/Protocol/DismissDelegate.swift
  IOS_Study/Global/Struct/Identifiers.swift
  IOS_Study/Screen/Chatting/Cell/TVC/AddChattingTVC.swift
  IOS_Study/Screen/Chatting/Cell/TVC/addChattingTVCTableViewCell.swift
  IOS_Study/Screen/Chatting/Controller/AddChattingVC.swift
  IOS_Study/Screen/Chatting/Controller/ChattingVC.swift
  IOS_Study/Screen/Chatting/Controller/StartChattingVC.swift
  IOS_Study/Screen/Chatting/Storyboard/AddChatting.storyboard
  IOS_Study/Screen/Chatting/Storyboard/Chatting.storyboard
  IOS_Study/Screen/Chatting/Storyboard/StartChatting.storyboard
  IOS_Study/Screen/NavigationBar/ChattingNB.xib
  IOS_Study/Screen/TabBar/Controller/MainTBC.swift
  IOS_Study/Support/Assets.xcassets/Clear_Button.imageset/Clear_Button.png
  IOS_Study/Support/Assets.xcassets/Clear_Button.imageset/Contents.json
Labels: 채팅탭, 호준, View, add
